version: '3'
services:
  elixir:
    build:
      context: ./services/elixir
      args:
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
    environment: 
      MIX_ENV: prod
    tty: true
    volumes:
      - ./src:/app
    ports: 
      - "8080:8080"
    command: /bin/bash -c "mix local.hex --force && mix run --no-halt"